<?php
global $places;

$places['SV'] = array(
    'SV-AH' => array("Ahuachapán",
        "Jujutla",
        "Atiquizaya",
        "Concepción de Ataco",
        "El Refugio",
        "Guaymango",
        "Apaneca",
        "San Francisco Menéndez",
        "San Lorenzo",
        "San Pedro Puxtla",
        "Tacuba",
        "Turín"),
    'SV-CA' => array(
        "Cinquera",
        "Villa Dolores",
        "Guacotecti",
        "Ilobasco",
        "Jutiapa",
        "San Isidro",
        "Sensuntepeque",
        "Ciudad de Tejutepeque",
        "Victoria",
    ),
    'SV-CH' => array(
        "Agua Caliente",
        "Arcatao",
        "Azacualpa",
        "Chalatenango",
        "Citalá",
        "Comalapa",
        "Concepción Quezaltepeque",
        "Dulce Nombre de María",
        "El Carrizal",
        "El Paraíso",
        "La Laguna",
        "La Palma",
        "La Reina",
        "Las Vueltas",
        "Nombre de Jesús",
        "Nueva Concepción",
        "Nueva Trinidad",
        "Ojos de Agua",
        "Potonico",
        "San Antonio de la Cruz",
        "San Antonio Los Ranchos",
        "San Fernando",
        "San Francisco Lempa",
        "San Francisco Morazán",
        "San Ignacio",
        "San Isidro Labrador",
        "San José Cancasque",
        "San José Las Flores",
        "San Luis del Carmen",
        "San Miguel de Mercedes",
        "San Rafael",
        "Santa Rita",
        "Tejutla",
    ), 'SV-CU' => array(
        "Candelaria",
        "Cojutepeque",
        "El Carmen",
        "El Rosario",
        "Monte San Juan",
        "Oratorio de Concepción",
        "San Bartolomé Perulapía",
        "San Cristóbal",
        "San José Guayabal",
        "San Pedro Perulapán",
        "San Rafael Cedros",
        "San Ramón",
        "Santa Cruz Analquito",
        "Santa Cruz Michapa",
        "Suchitoto",
        "Tenancingo",
    ), 'SV-LI' => array(
        "Antiguo Cuscatlán",
        "Chiltiupán",
        "Ciudad Arce",
        "Colón",
        "Comasagua",
        "Huizúcar",
        "Jayaque",
        "Jicalapa",
        "La Libertad",
        "Santa Tecla",
        "Nuevo Cuscatlán",
        "Opico",
        "Quezaltepeque",
        "Sacacoyo",
        "San José Villanueva",
        "San Matías",
        "San Pablo Tacachico",
        "Talnique",
        "Tamanique",
        "Teotepeque",
        "Tepecoyo",
        "Zaragoza",
    ), 'SV-PA' => array(
        "Cuyultitán",
        "El Rosario",
        "Jerusalén",
        "Mercedes La Ceiba",
        "Olocuilta",
        "Paraíso de Osorio",
        "San Antonio Masahuat",
        "San Emigdio",
        "San Francisco Chinameca",
        "San Juan Nonualco",
        "San Juan Talpa",
        "San Juan Tepezontes",
        "San Luis La Herradura",
        "San Luis Talpa",
        "San Miguel Tepezontes",
        "San Pedro Masahuat",
        "San Pedro Nonualco",
        "San Rafael Obrajuelo",
        "Santa María Ostuma",
        "Santiago Nonualco",
        "Tapalhuaca",
        "Zacatecoluca",
    ), 'SV-UN' => array(
        "Anamorós",
        "Bolívar",
        "Concepción de Oriente",
        "Conchagua",
        "El Carmen",
        "El Sauce",
        "Intipucá",
        "La Unión",
        "Lislique",
        "Meanguera del Golfo",
        "Nueva Esparta",
        "Pasaquina",
        "Polorós",
        "San Alejo",
        "San José",
        "Santa Rosa de Lima",
        "Yayantique",
        "Yucuayquín",
    ), 'SV-MO' => array(
        "Arambala",
        "Cacaopera",
        "Chilanga",
        "Corinto",
        "Delicias de Concepción",
        "El Divisadero",
        "El Rosario",
        "Gualococti",
        "Guatajiagua",
        "Joateca",
        "Jocoaitique",
        "Jocoro",
        "Lolotiquillo",
        "Meanguera",
        "Osicala",
        "Perquín",
        "San Carlos",
        "San Fernando",
        "San Francisco Gotera",
        "San Isidro",
        "San Simón",
        "Sensembra",
        "Sociedad",
        "Torola",
        "Yamabal",
        "Yoloaiquín",

    ), 'SV-SM' => array(
        "Carolina",
        "Chapeltique",
        "Chinameca",
        "Chirilagua",
        "Ciudad Barrios",
        "Comacarán",
        "El Tránsito",
        "Lolotique",
        "Moncagua",
        "Nueva Guadalupe",
        "Nuevo Edén de San Juan",
        "Quelepa",
        "San Antonio",
        "San Gerardo",
        "San Jorge",
        "San Luis de la Reina",
        "San Miguel",
        "San Rafael",
        "Sesori",
        "Uluazapa",
    ), 'SV-SS' => array(
        "Aguilares",
        "Apopa",
        "Ayutuxtepeque",
        "Cuscatancingo",
        "Delgado",
        "El Paisnal",
        "Guazapa",
        "Ilopango",
        "Mejicanos",
        "Nejapa",
        "Panchimalco",
        "Rosario de Mora",
        "San Marcos",
        "San Martín",
        "San Salvador",
        "Santiago Texacuangos",
        "Santo Tomás",
        "Soyapango",
        "Tonacatepeque",
    ), 'SV-SV' => array(
        "Apastepeque",
        "Guadalupe",
        "San Cayetano Istepeque",
        "San Esteban Catarina",
        "San Ildefonso",
        "San Lorenzo",
        "San Sebastián",
        "Santa Clara",
        "Santo Domingo",
        "San Vicente",
        "Tecoluca",
        "Tepetitán",
        "Verapaz",
    ), 'SV-SA' => array(
        "Candelaria de la Frontera",
        "Chalchuapa",
        "Coatepeque",
        "El Congo",
        "El Porvenir",
        "Masahuat",
        "Metapán",
        "San Antonio Pajonal",
        "San Sebastián Salitrillo",
        "Santa Ana",
        "Santa Rosa Guachipilín",
        "Santiago de la Frontera",
        "Texistepeque",
    ), 'SV-SO' => array(
        "Acajutla",
        "Armenia",
        "Caluco",
        "Cuisnahuat",
        "Izalco",
        "Juayúa",
        "Nahuizalco",
        "Nahulingo",
        "Salcoatitán",
        "San Antonio del Monte",
        "San Julián",
        "Santa Catarina Masahuat",
        "Santa Isabel Ishuatán",
        "Santo Domingo",
        "Sonsonate",
        "Sonzacate",
    ), 'SV-US' => array(
        "Alegría",
        "Berlín",
        "California",
        "Concepción Batres",
        "El Triunfo",
        "Ereguayquín",
        "Estanzuelas",
        "Jiquilisco",
        "Jucuapa",
        "Jucuarán",
        "Mercedes Umaña",
        "Nueva Granada",
        "Ozatlán",
        "Puerto El Triunfo",
        "San Agustín",
        "San Buenaventura",
        "San Dionisio",
        "San Francisco Javier",
        "Santa Elena",
        "Santa María",
        "Santiago de María",
        "Tecapán",
        "Usulután",
    ),
);
